-- =============================================
-- LIFEQUEST 2.0 - Base de datos MySQL
-- =============================================

CREATE DATABASE IF NOT EXISTS LIFEQUEST2;
USE LIFEQUEST2;

CREATE TABLE NIVEL(
ID_NIVEL INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_NIVEL VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(250) NOT NULL,
EXPERIENCIA_REQUERIDA INT NOT NULL,
CONSTRAINT UO_NOMBRE_NIVEL UNIQUE(NOMBRE_NIVEL),
CONSTRAINT CHK_EXP_NIVEL CHECK  (EXPERIENCIA_REQUERIDA >=0)
);

CREATE TABLE ADMINISTRADOR(
ID_ADMINISTRADOR INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
CORREO VARCHAR(100) NOT NULL,
CONTRASENA VARCHAR(255) NOT NULL,
ROL VARCHAR(50) NOT NULL,
CONSTRAINT UO_ADMIN_CORREO UNIQUE(CORREO),
CONSTRAINT CHK_ROL_ADMIN CHECK( ROL IN ('SUPERADMIN','ADMIN','MODERADOR')));

CREATE TABLE RECOMPENSA(
ID_RECOMPENSA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
MONEDAS_REQUERIDAS INT NOT NULL DEFAULT 0,
CONSTRAINT UO_RECOMPENSA_NOMBRE UNIQUE(NOMBRE),
CONSTRAINT CHK_TIPO_RECOMPENSA CHECK( TIPO IN('MONEDAS','EXPERIENCIA','ITEM','MASCOTA','ACCESORIO','COFRE')),
CONSTRAINT CHK_PUNTOS_RECOMPENSA_ CHECK(MONEDAS_REQUERIDAS >=0));

CREATE TABLE LOGRO_CATALOGO(
ID_LOGRO_CATALOGO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL,
TIPO_CONDICION VARCHAR(50) NOT NULL,
VALOR_CONDICION INT NOT NULL,
CONSTRAINT UO_LOGRO_NOMBRE UNIQUE (NOMBRE),
CONSTRAINT CHK_TIPO_CONDICION CHECK( TIPO_CONDICION IN ('RACHA','NIVEL','MISIONES','HABITOS','MONEDAS','VIDEOJUEGOS')),
CONSTRAINT CHK_VALOR_CONDICION CHECK(VALOR_CONDICION >=0));

CREATE TABLE CATALOGO_MASCOTA(
ID_CATALOGO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(255),
ID_EVOLUCION INT NULL,
EVOLUCION VARCHAR(100),
CONSTRAINT UO_CATALOGO_MASCOTA_NOMBRE UNIQUE (NOMBRE));

CREATE TABLE ACCESORIOS(
ID_ACCESORIOS INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR (100) NOT NULL,
TIPO VARCHAR(50) NOT NULL,
PRECIO INT NOT NULL,
IMAGEN VARCHAR(255),
CONSTRAINT UO_ACCESORIO_NOMBRE UNIQUE (NOMBRE),
CONSTRAINT CHK_PRECIO_ACCESORIOS CHECK(PRECIO>=0),
CONSTRAINT CHK_TIPO_ACCESORIOS CHECK (TIPO IN ('SOMBRERO','ROPA', 'GAFAS','MOCHILA','MASCOTA','EFECTO','ALAS')));

CREATE TABLE ITEM_TIENDA(
ID_ITEM INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
PRECIO INT NOT NULL,
DESCRIPCION VARCHAR(255),
IMAGEN VARCHAR(255),
RARIDAD VARCHAR(50),
DISPONIBLE BOOLEAN NOT NULL DEFAULT TRUE,
CONSTRAINT UO_ITEM_NOMBRE UNIQUE (NOMBRE),
CONSTRAINT CHK_PRECIO_ITEM CHECK (PRECIO>=0),
CONSTRAINT CHK_TIPO_ITEM CHECK (TIPO IN ('MASCOTA','ACCESORIO','COFRE','ROPA','SOMBRERO')));

CREATE TABLE VIDEOJUEGO (
    ID_VIDEOJUEGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PLATAFORMA VARCHAR(50) NOT NULL,
    ICONO VARCHAR(255),
    CONSTRAINT UQ_VIDEOJUEGO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CHK_PLATAFORMA_VIDEOJUEGO
    CHECK (PLATAFORMA IN ('PC','ANDROID','IOS','PLAYSTATION','XBOX','MULTIPLATAFORMA')));

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT (CURRENT_DATE),
    EXPERIENCIA_TOTAL INT NOT NULL DEFAULT 0,
    MONEDAS INT NOT NULL DEFAULT 0,
    ULTIMA_ACTIVIDAD DATE,
    FOTO_PERFIL_URL VARCHAR(255),
    FK_ID_NIVEL INT NOT NULL,
    CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT CHK_EXPERIENCIA CHECK (EXPERIENCIA_TOTAL >= 0),
    CONSTRAINT CHK_MONEDAS CHECK (MONEDAS >= 0),
    CONSTRAINT FK_USUARIO_NIVEL
    FOREIGN KEY (FK_ID_NIVEL) REFERENCES NIVEL(ID_NIVEL));

CREATE TABLE PERFIL_USUARIO (
    ID_PERFIL INT AUTO_INCREMENT PRIMARY KEY,
    EDAD INT NOT NULL,
    PESO DECIMAL(5,2) NOT NULL,
    ALTURA DECIMAL(4,2) NOT NULL,
    OBJETIVO VARCHAR(100) NOT NULL,
    NIVEL_FISICO VARCHAR(20) NOT NULL,
    TIEMPO_DISPONIBLE VARCHAR(20) NOT NULL,
    CONDICION_FISICA VARCHAR(20),
    FK_ID_USUARIO INT NOT NULL,
    CONSTRAINT UQ_PERFIL_USUARIO UNIQUE (FK_ID_USUARIO),
    CONSTRAINT CHK_EDAD CHECK (EDAD >= 10 AND EDAD <= 120),
    CONSTRAINT CHK_PESO CHECK (PESO > 0),
    CONSTRAINT CHK_ALTURA CHECK (ALTURA > 0),
    CONSTRAINT CHK_NIVEL_FISICO CHECK (NIVEL_FISICO IN('PRINCIPIANTE','INTERMEDIO','AVANZADO')),
    CONSTRAINT CHK_TIEMPO_DISPONIBLE CHECK (TIEMPO_DISPONIBLE IN ('15_MIN','30_MIN','1_HORA','2_HORAS','MAS_DE_2_HORAS')),
    CONSTRAINT FK_PERFIL_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE CONFIGURACION (
    ID_CONFIGURACION INT AUTO_INCREMENT PRIMARY KEY,
    IDIOMA VARCHAR(20) NOT NULL DEFAULT 'ESPAÑOL',
    TEMA VARCHAR(10) NOT NULL DEFAULT 'CLARO',
    NOTIFICACIONES BOOLEAN NOT NULL DEFAULT TRUE,
    GOOGLE_VINCULADO BOOLEAN NOT NULL DEFAULT FALSE,
    FK_ID_USUARIO INT NOT NULL,
    CONSTRAINT UQ_CONFIGURACION_USUARIO UNIQUE (FK_ID_USUARIO),
    CONSTRAINT CHK_IDIOMA CHECK (IDIOMA IN ('ESPAÑOL','INGLES')),
    CONSTRAINT CHK_TEMA CHECK (TEMA IN ('CLARO','OSCURO')),
    CONSTRAINT FK_CONFIGURACION_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE META (
    ID_META INT AUTO_INCREMENT PRIMARY KEY,
    TITULO_META VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    FK_ID_USUARIO INT NOT NULL,
    CONSTRAINT CHK_ESTADO_META CHECK (ESTADO IN ('ACTIVA','PAUSADA','FINALIZADA','CANCELADA')),
    CONSTRAINT CHK_FECHAS_META CHECK (
	FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_META_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE HABITO (
    ID_HABITO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FRECUENCIA VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
    OBJETIVO_CANTIDAD INT,
    FECHA_CREACION DATE NOT NULL DEFAULT (CURRENT_DATE),
    FK_ID_USUARIO INT NOT NULL,
    CONSTRAINT CHK_FRECUENCIA_HABITO CHECK (FRECUENCIA IN ('DIARIO','SEMANAL','MENSUAL')),
    CONSTRAINT CHK_ESTADO_HABITO CHECK (ESTADO IN ('ACTIVO','PAUSADO','FINALIZADO')),
    CONSTRAINT FK_HABITO_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE RACHA (
    ID_RACHA INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(20) NOT NULL,
    ACTUAL INT NOT NULL DEFAULT 0,
    MAXIMA INT NOT NULL DEFAULT 0,
    ULTIMA_FECHA DATE NOT NULL,
    FK_ID_USUARIO INT NOT NULL,
    CONSTRAINT CHK_TIPO_RACHA CHECK (TIPO IN ('HABITOS','MISIONES','VIDEOJUEGOS')),
    CONSTRAINT CHK_RACHA_ACTUAL CHECK (ACTUAL >= 0),
    CONSTRAINT CHK_RACHA_MAXIMA CHECK (MAXIMA >= 0),
    CONSTRAINT UQ_RACHA_USUARIO_TIPO UNIQUE (FK_ID_USUARIO, TIPO),
    CONSTRAINT FK_RACHA_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE PLANTILLA_MISION (
    ID_PLANTILLA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    DIFICULTAD VARCHAR(20) NOT NULL,
    EXP_BASE INT NOT NULL DEFAULT 0,
    MONEDAS INT NOT NULL DEFAULT 0,
    ACTIVA BOOLEAN NOT NULL DEFAULT TRUE,
    TIEMPO_MINIMO INT,
    TIEMPO_MAXIMO INT,
    NIVEL_MINIMO INT,
    FK_ID_ADMINISTRADOR INT NOT NULL,
    CONSTRAINT UQ_PLANTILLA_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CHK_TIPO_PLANTILLA CHECK (TIPO IN ('HABITO','VIDEOJUEGO','SALUD','ESTUDIO','PRODUCTIVIDAD','PERSONAL')),
    CONSTRAINT CHK_DIFICULTAD_PLANTILLA CHECK (DIFICULTAD IN ('FACIL','MEDIA','DIFICIL')),
    CONSTRAINT CHK_EXP_BASE CHECK (EXP_BASE >= 0),
    CONSTRAINT CHK_MONEDAS_BASE CHECK (MONEDAS >= 0),
    CONSTRAINT FK_PLANTILLA_ADMINISTRADOR
    FOREIGN KEY (FK_ID_ADMINISTRADOR)REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

CREATE TABLE LOGROS (
    ID_LOGRO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_DESBLOQUEO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_LOGRO_CATALOGO INT NOT NULL,
    CONSTRAINT UQ_LOGRO_USUARIO UNIQUE (FK_ID_USUARIO, FK_ID_LOGRO_CATALOGO),
    CONSTRAINT FK_LOGROS_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    MOSTRADO BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_LOGROS_CATALOGO
    FOREIGN KEY (FK_ID_LOGRO_CATALOGO)REFERENCES LOGRO_CATALOGO(ID_LOGRO_CATALOGO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE RECOMPENSA_USUARIO (
    ID_RECOMPENSA_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_OBTENIDA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD INT NOT NULL DEFAULT 1,
    ORIGEN VARCHAR(30),
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_RECOMPENSA INT NOT NULL,
    CONSTRAINT CHK_CANTIDAD_RECOMPENSA CHECK (CANTIDAD > 0),
    CONSTRAINT FK_RECOMPENSA_USUARIO_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_RECOMPENSA_USUARIO_RECOMPENSA
    FOREIGN KEY (FK_ID_RECOMPENSA)REFERENCES RECOMPENSA(ID_RECOMPENSA)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE MASCOTA (
    ID_MASCOTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    NIVEL INT NOT NULL DEFAULT 1,
    EXPERIENCIA INT NOT NULL DEFAULT 0,
    ENERGIA INT NOT NULL DEFAULT 100,
    FELICIDAD INT NOT NULL DEFAULT 100,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    FAVORITA BOOLEAN NOT NULL DEFAULT FALSE,
    FECHA_OBTENCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_CATALOGO INT NOT NULL,
    CONSTRAINT CHK_NIVEL_MASCOTA CHECK (NIVEL >= 1),
    CONSTRAINT CHK_EXP_MASCOTA CHECK (EXPERIENCIA >= 0),
    CONSTRAINT CHK_ENERGIA CHECK (ENERGIA BETWEEN 0 AND 100),
    CONSTRAINT CHK_FELICIDAD CHECK (FELICIDAD BETWEEN 0 AND 100),
    CONSTRAINT CHK_ESTADO_MASCOTA CHECK (ESTADO IN ('ACTIVA','DESCANSANDO','INACTIVA')),
    CONSTRAINT FK_MASCOTA_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_MASCOTA_CATALOGO
    FOREIGN KEY (FK_ID_CATALOGO)REFERENCES CATALOGO_MASCOTA(ID_CATALOGO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

CREATE TABLE COMPRA (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_COMPRA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD INT NOT NULL DEFAULT 1,
    ESTADO VARCHAR(20),
    PRECIO_UNITARIO INT NOT NULL,
    PRECIO_TOTAL INT NOT NULL,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_ITEM INT NOT NULL,
    CONSTRAINT CHK_CANTIDAD_COMPRA CHECK (CANTIDAD > 0),
    CONSTRAINT CHK_PRECIO_UNITARIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT CHK_PRECIO_TOTAL CHECK (PRECIO_TOTAL >= 0),
    CONSTRAINT FK_COMPRA_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_COMPRA_ITEM
    FOREIGN KEY (FK_ID_ITEM)REFERENCES ITEM_TIENDA(ID_ITEM)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

CREATE TABLE USUARIO_VIDEOJUEGO (
    ID_USUARIO_VIDEOJUEGO INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_JUEGO VARCHAR(100) NOT NULL,
    VINCULADO BOOLEAN NOT NULL DEFAULT TRUE,
    FECHA_VINCULACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_VIDEOJUEGO INT NOT NULL,
    ULTIMA_SINCRONIZACION DATETIME,
    CONSTRAINT UQ_USUARIO_VIDEOJUEGO UNIQUE (FK_ID_USUARIO, FK_ID_VIDEOJUEGO),
    CONSTRAINT FK_USUARIO_VIDEOJUEGO_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_USUARIO_VIDEOJUEGO_VIDEOJUEGO
    FOREIGN KEY (FK_ID_VIDEOJUEGO)REFERENCES VIDEOJUEGO(ID_VIDEOJUEGO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE MISION_VIDEOJUEGO (
    ID_MISION_VIDEOJUEGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    DIFICULTAD VARCHAR(20) NOT NULL,
    EXP_OTORGADA INT NOT NULL DEFAULT 0,
    MONEDAS_OTORGADAS INT NOT NULL DEFAULT 0,
    ACTIVA BOOLEAN NOT NULL DEFAULT TRUE,
    FK_ID_VIDEOJUEGO INT NOT NULL,
    CONSTRAINT CHK_DIFICULTAD_MISION_VIDEOJUEGO CHECK (DIFICULTAD IN ('FACIL','MEDIA','DIFICIL')),
    CONSTRAINT CHK_EXP_MISION_VIDEOJUEGO CHECK (EXP_OTORGADA >= 0),
    CONSTRAINT CHK_MONEDAS_MISION_VIDEOJUEGO CHECK (MONEDAS_OTORGADAS >= 0),
    CONSTRAINT FK_MISION_VIDEOJUEGO
    FOREIGN KEY (FK_ID_VIDEOJUEGO)
REFERENCES VIDEOJUEGO(ID_VIDEOJUEGO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE MISIONES (
    ID_MISION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MISION VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    DIFICULTAD VARCHAR(20) NOT NULL,
    EXP_OTORGADA INT NOT NULL DEFAULT 0,
    MONEDAS_OTORGADAS INT NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_LIMITE DATETIME,
    FK_ID_META INT NOT NULL,
    FK_ID_PLANTILLA INT NOT NULL,
    FK_ID_ADMINISTRADOR INT NOT NULL,
    FK_ID_RECOMPENSA INT,
    CONSTRAINT CHK_DIFICULTAD_MISION CHECK (DIFICULTAD IN ('FACIL','MEDIA','DIFICIL')),
    CONSTRAINT CHK_ESTADO_MISION CHECK (ESTADO IN ('PENDIENTE','EN_PROGRESO','COMPLETADA','CANCELADA','VENCIDA')),
    CONSTRAINT CHK_EXP_OTORGADA CHECK (EXP_OTORGADA >= 0),
    CONSTRAINT CHK_MONEDAS_OTORGADAS CHECK (MONEDAS_OTORGADAS >= 0),
    CONSTRAINT CHK_FECHA_LIMITE CHECK (FECHA_LIMITE IS NULL OR FECHA_LIMITE >= FECHA_CREACION),
    CONSTRAINT FK_MISION_META
    FOREIGN KEY (FK_ID_META)REFERENCES META(ID_META)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_MISION_PLANTILLA
    FOREIGN KEY (FK_ID_PLANTILLA)REFERENCES PLANTILLA_MISION(ID_PLANTILLA)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT FK_MISION_ADMINISTRADOR
    FOREIGN KEY (FK_ID_ADMINISTRADOR)REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT FK_MISION_RECOMPENSA
    FOREIGN KEY (FK_ID_RECOMPENSA)REFERENCES RECOMPENSA(ID_RECOMPENSA)
    ON DELETE SET NULL
    ON UPDATE CASCADE);

CREATE TABLE PROGRESO (
    ID_PROGRESO INT AUTO_INCREMENT PRIMARY KEY,
    PORCENTAJE DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    INTENTOS INT DEFAULT 0,
    FECHA_INICIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    FECHA_FINALIZACION DATETIME NULL,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_MISION INT NOT NULL,
    CONSTRAINT UQ_PROGRESO_USUARIO_MISION UNIQUE (FK_ID_USUARIO, FK_ID_MISION),
    CONSTRAINT CHK_PORCENTAJE CHECK (PORCENTAJE BETWEEN 0 AND 100),
    CONSTRAINT CHK_ESTADO_PROGRESO CHECK (ESTADO IN ('PENDIENTE','EN_PROGRESO','COMPLETADA','CANCELADA')),
    CONSTRAINT FK_PROGRESO_USUARIO
    FOREIGN KEY (FK_ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_PROGRESO_MISION
    FOREIGN KEY (FK_ID_MISION)REFERENCES MISIONES(ID_MISION)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE EVIDENCIA (
    ID_EVIDENCIA INT AUTO_INCREMENT PRIMARY KEY,
    URL_FOTO VARCHAR(255) NOT NULL,
    FECHA_ENVIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    COMENTARIO_ADMIN VARCHAR(255),
    FK_ID_PROGRESO INT NOT NULL,
    FK_ID_ADMINISTRADOR INT,
    CONSTRAINT CHK_ESTADO_EVIDENCIA CHECK (ESTADO IN ('PENDIENTE','VALIDADA','RECHAZADA')),
    CONSTRAINT FK_EVIDENCIA_PROGRESO
    FOREIGN KEY (FK_ID_PROGRESO)REFERENCES PROGRESO(ID_PROGRESO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_EVIDENCIA_ADMINISTRADOR
    FOREIGN KEY (FK_ID_ADMINISTRADOR)REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
    ON DELETE SET NULL
    ON UPDATE CASCADE);

CREATE TABLE HABITO_REGISTRO (
    ID_REGISTRO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    COMPLETADO BOOLEAN NOT NULL DEFAULT FALSE,
    HORA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OBSERVACION VARCHAR(255),
    FK_ID_HABITO INT NOT NULL,
    CONSTRAINT UQ_HABITO_FECHA UNIQUE (FK_ID_HABITO, FECHA),
    CONSTRAINT FK_HABITO_REGISTRO
    FOREIGN KEY (FK_ID_HABITO) REFERENCES HABITO(ID_HABITO)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE MASCOTA_ACCESORIO (
    ID_MASCOTA_ACCESORIO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_EQUIPADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EQUIPADO BOOLEAN NOT NULL DEFAULT TRUE,
    FK_ID_MASCOTA INT NOT NULL,
    FK_ID_ACCESORIO INT NOT NULL,
    CONSTRAINT UQ_MASCOTA_ACCESORIO UNIQUE (FK_ID_MASCOTA, FK_ID_ACCESORIO),
    CONSTRAINT FK_MASCOTA_ACCESORIO_MASCOTA
    FOREIGN KEY (FK_ID_MASCOTA)REFERENCES MASCOTA(ID_MASCOTA)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT FK_MASCOTA_ACCESORIO_ACCESORIOS
    FOREIGN KEY (FK_ID_ACCESORIO)REFERENCES ACCESORIOS(ID_ACCESORIOS)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
